
// idPedido,idComercioProducto,cantidadCompra,precioUnidad;
RespuestaServerCloud **----------** Array [
  Object {
    "idComercio": "1",
    "idPedido": "196",
  },
  Object {
    "idComercio": "6",
    "idPedido": "197",
  },
  Object {
    "idComercio": "87",
    "idPedido": "198",
  },
  Object {
    "Cantidad": 1,
    "cantidadProducto": "13",
    "descripcionProducto": "prueba pan",
    "detalleComercio": "Restaurante de comida tradicional vallecaucana",
    "idComercio": "1",
    "idComercioProducto": "41",
    "idProducto": "24",
    "imagenComercio": "http://andresteccorp.club/TesisAndres/imagenesProyecto/imagenesProyecto/imagenComercio/antinos.jpg",
    "imagenProducto": "http://colombiapanysabor.com/images/panqueso-queso-cps-g.jpg",
    "nombreProducto": "Pan",
    "nombreTienda": "Antinos",
    "precioUnidadProducto": "4000",
  },
  Object {
    "Cantidad": 1,
    "cantidadProducto": "100",
    "descripcionProducto": "Refrescantes gaseosas de diferentes sabores",
    "detalleComercio": "Restaurante de comida tradicional vallecaucana",
    "idComercio": "1",
    "idComercioProducto": "34",
    "idProducto": "25",
    "imagenComercio": "http://andresteccorp.club/TesisAndres/imagenesProyecto/imagenesProyecto/imagenComercio/antinos.jpg",
    "imagenProducto": "http://andresteccorp.club/TesisAndres/imagenesProyecto/imagenesProyecto/imagenProductosComercio/gaseosa.jpg",
    "nombreProducto": "Gaseosa",
    "nombreTienda": "Antinos",
    "precioUnidadProducto": "2500",
  },
  Object {
    "Cantidad": 1,
    "cantidadProducto": "20",
    "descripcionProducto": "prueba del producto lechona",
    "detalleComercio": "Comidas tradicionales Colombianas y comidas rapidas",
    "idComercio": "6",
    "idComercioProducto": "20",
    "idProducto": "20",
    "imagenComercio": "http://andresteccorp.club/TesisAndres/imagenesProyecto/imagenesProyecto/imagenComercio/peperestaurant.jpg",
    "imagenProducto": "https://img.pystatic.com/products/domi_d72de548510c1a1086d681bfb5d7886f.jpg",
    "nombreProducto": "Lechona",
    "nombreTienda": "PepeRestaurante",
    "precioUnidadProducto": "2700",
  },
  Object {
    "Cantidad": 1,
    "cantidadProducto": "8",
    "descripcionProducto": "Deliciosa bandeja paisa preparada con Arroz blanco chorizo, platano maduro,chicharron,carne molida y",
    "detalleComercio": "Comidas tradicionales Colombianas y comidas rapidas",
    "idComercio": "6",
    "idComercioProducto": "18",
    "idProducto": "18",
    "imagenComercio": "http://andresteccorp.club/TesisAndres/imagenesProyecto/imagenesProyecto/imagenComercio/peperestaurant.jpg",
    "imagenProducto": "https://media-cdn.tripadvisor.com/media/photo-s/02/ea/30/5d/little-city-el-pueblito.jpg",
    "nombreProducto": "Bandeja Paisa",
    "nombreTienda": "PepeRestaurante",
    "precioUnidadProducto": "12000",
  },
  Object {
    "Cantidad": 1,
    "cantidadProducto": "100",
    "descripcionProducto": "Burritos",
    "detalleComercio": "Autentico Sabor mexicano",
    "idComercio": "87",
    "idComercioProducto": "126",
    "idProducto": "74",
    "imagenComercio": "http://andresteccorp.club/TesisAndres/imagenesProyecto/imagenesProyecto/imagenComercio/aztecas.jpg",
    "imagenProducto": "http://andresteccorp.club/TesisAndres/imagenesProyecto/imagenesProyecto/imagenProductosComercio/burritosMexicanos.jpg",
    "nombreProducto": "Burritos Mexicanos",
    "nombreTienda": "Aztecas",
    "precioUnidadProducto": "12000",
  },
]